### ISSUE TITLE
INFOGRAFIA REALIDAD AUMENTADA

### ISSUE THREAD

**Issue by omarlopz** [SistemasTecTlaxiaco/infografia-omarlopz#1]
![INFOGRAFIA REALIDAD AUMENTADA](https://user-images.githubusercontent.com/71897222/111112128-3e462280-8525-11eb-8731-004e5f042286.png)

**Comment by AxayacatlS** [comment]
Calificación: 17

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
